# Generated by Django 6.0.1 on 2026-09-27 13:18

import core.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('voting_enabled', models.BooleanField(default=False)),
                ('voter_login_mode', models.CharField(choices=[('activator_id', 'Activator and student ID'), ('activator_pin', 'Activator and PIN'), ('sms_pin', 'SMS PIN')], default='activator_pin', max_length=20)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='election_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.election')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('has_voted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('voting_pin_hash', models.CharField(blank=True, default='', max_length=128)),
                ('voting_pin_created_at', models.DateTimeField(blank=True, null=True)),
                ('voting_pin_attempts', models.PositiveSmallIntegerField(default=0)),
                ('voter_session_expires_at', models.DateTimeField(blank=True, null=True)),
                ('voter_activation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.election')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(blank=True)),
                ('ballot_number', models.PositiveIntegerField(default=1)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('candidate', 'Candidate'), ('yes', 'Yes'), ('no', 'No'), ('skip', 'Skipped')], default='candidate', max_length=10)),
                ('voter_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.position')),
            ],
        ),
        migrations.CreateModel(
            name='VoterSMSAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('disabled', 'Disabled'), ('skipped', 'Skipped'), ('generated', 'Generated')], db_index=True, max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_category', models.CharField(blank=True, max_length=100)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_sms_attempts', to='core.election')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_attempts', to='core.student')),
            ],
            options={
                'ordering': ('-attempted_at',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superuser', 'Superuser'), ('staff', 'Staff'), ('activator', 'Activator')], default='staff', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('assigned_election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='core.election')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('role', 'superuser'), ('is_superuser', True), ('assigned_election__isnull', True)), models.Q(('role__in', ['staff', 'activator']), ('is_superuser', False), ('assigned_election__isnull', False)), _connector='OR'), name='user_role_election_consistent')],
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('election', 'student_id'), name='unique_election_student'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('position', 'ballot_number'), name='unique_position_ballot_number'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('student',), name='unique_student_candidate'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('candidate__isnull', True), ('choice', 'skip')), models.Q(('candidate__isnull', False), ('choice__in', ('candidate', 'yes', 'no'))), _connector='OR'), name='vote_choice_candidate_consistency'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter_hash', 'position')},
        ),
    ]
