# Generated by Django 5.2.7 on 2026-01-24 11:46

import django.db.models.deletion
from django.db import migrations, models


def backfill_existing_students(apps, schema_editor):
    """Set election_id=2 for all existing students that don't have an election."""
    Student = apps.get_model('core', 'Student')
    Election = apps.get_model('core', 'Election')
    try:
        election_2 = Election.objects.get(pk=2)
        Student.objects.filter(election__isnull=True).update(election=election_2)
    except Election.DoesNotExist:
        # If election 2 doesn't exist, leave as null
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.election'),
        ),
        migrations.RunPython(backfill_existing_students, migrations.RunPython.noop),
    ]
