# Generated by Django 5.2.7 on 2026-01-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_election_id_to_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='election',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.election'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('election', 'student_id'), name='unique_election_student'),
        ),
    ]
