# Generated by Django 5.2.7 on 2026-01-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_composite_unique_constraint_to_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ballot_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
