# Generated by Django 5.2.7 on 2026-01-30 22:27

from django.db import migrations


def assign_ballot_numbers(apps, schema_editor):
    """
    Assign ballot numbers starting from 1 for each position.
    This ensures each position has candidates numbered 1, 2, 3, etc.
    """
    Candidate = apps.get_model('core', 'Candidate')
    Position = apps.get_model('core', 'Position')
    
    # Get all positions
    positions = Position.objects.all()
    
    # For each position, assign ballot numbers 1, 2, 3... to its candidates
    for position in positions:
        candidates = Candidate.objects.filter(position=position).order_by('id')
        
        # Assign ballot numbers starting from 1 for this position
        for index, candidate in enumerate(candidates, 1):
            candidate.ballot_number = index
            candidate.save()


def reverse_assign_ballot_numbers(apps, schema_editor):
    """
    Reverse function - set all ballot numbers back to 1
    """
    Candidate = apps.get_model('core', 'Candidate')
    Candidate.objects.all().update(ballot_number=1)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_ballot_number_to_candidate'),
    ]

    operations = [
        migrations.RunPython(assign_ballot_numbers, reverse_assign_ballot_numbers)
    ]
