# Generated by Django 5.2.7 on 2026-01-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assign_ballot_numbers_to_existing_candidates'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('position', 'ballot_number'), name='unique_position_ballot_number'),
        ),
    ]
