# Generated by Django 5.2.7 on 2026-01-30 22:51

from django.db import migrations


def fix_ballot_numbers_per_position(apps, schema_editor):
    """
    Fix ballot numbers to start from 1 for each position.
    This ensures each position has candidates numbered 1, 2, 3, etc.
    """
    Candidate = apps.get_model('core', 'Candidate')
    Position = apps.get_model('core', 'Position')
    
    # Get all positions
    positions = Position.objects.all()
    
    # For each position, assign ballot numbers 1, 2, 3... to its candidates
    for position in positions:
        candidates = Candidate.objects.filter(position=position).order_by('id')
        
        # Assign ballot numbers starting from 1 for this position
        for index, candidate in enumerate(candidates, 1):
            candidate.ballot_number = index
            candidate.save()


def reverse_fix_ballot_numbers_per_position(apps, schema_editor):
    """
    Reverse function - no action needed as this is a corrective migration
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_ballot_number_constraint'),
    ]

    operations = [
        migrations.RunPython(fix_ballot_numbers_per_position, reverse_fix_ballot_numbers_per_position)
    ]
