# Generated by Django 5.2.7 on 2026-01-31 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fix_ballot_numbers_per_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('student',), name='unique_student_candidate'),
        ),
    ]
