# Generated by Django 5.2.7 on 2026-02-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_candidate_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
