# Generated by Django 6.0.1 on 2026-02-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_change_photo_url_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
