# Generated by Django 6.0.1 on 2026-09-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_user_options_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='is_active',
            new_name='voting_enabled',
        ),
    ]
