# Generated by Django 6.0.1 on 2026-09-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_is_active_election_voting_enabled'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='election',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='election_end_after_start'),
        ),
    ]
