# Generated by Django 6.0.1 on 2026-09-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_election_election_end_after_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('yes', 'Yes'), ('no', 'No')], default='candidate', max_length=10),
        ),
    ]
