# Generated by Django 6.0.1 on 2026-09-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_add_choice_to_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.PROTECT,
                to="core.candidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(choice="skip", candidate__isnull=True)
                    | models.Q(
                        choice__in=("candidate", "yes", "no"),
                        candidate__isnull=False,
                    )
                ),
                name="vote_choice_candidate_consistency",
            ),
        ),
    ]
