# Generated by Django 6.0.1 on 2026-09-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_allow_skipped_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('yes', 'Yes'), ('no', 'No'), ('skip', 'Skipped')], default='candidate', max_length=10),
        ),
    ]
