# Generated by Django 6.0.1 on 2026-09-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_vote_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='voting_pin_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='voting_pin_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='voting_pin_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
