# Generated by Django 6.0.1 on 2026-09-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_student_voting_pin_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='voter_session_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
