# Generated by Django 6.0.1 on 2026-09-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_voter_sms_attempt_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votersmsattempt',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('disabled', 'Disabled'), ('skipped', 'Skipped'), ('generated', 'Generated')], db_index=True, max_length=20),
        ),
    ]
