"""
Django settings for evoting project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from decouple import RepositoryEnv, Config

BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------------
# Load .env if it exists (LOCAL ONLY)
# --------------------------------------------------
ENV_PATH = BASE_DIR / ".env"
env = Config(RepositoryEnv(ENV_PATH)) if ENV_PATH.exists() else None


def get_env(key, default=None, cast=None):
    if key in os.environ:
        value = os.environ.get(key)
    elif env:
        value = env(key, default=default)
    else:
        value = default

    if cast and value is not None:
        # Special handling for bool to properly convert string "true"/"false"
        if cast == bool:
            if isinstance(value, str):
                return value.lower() in ('true', '1', 'yes', 'on')
            return bool(value)
        return cast(value)
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("No DJANGO_SECRET_KEY set for production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env('DEBUG', default=False, cast=bool)

# Force DEBUG=False in production environments
if get_env("RAILWAY_ENVIRONMENT") or get_env("RAILWAY_PUBLIC_DOMAIN"):
    DEBUG = False

# Production security settings
if not DEBUG:
    # Security middleware settings for production
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Restrict ALLOWED_HOSTS in production
    ALLOWED_HOSTS = []
    
    # Add Railway domain
    railway_domain = get_env("RAILWAY_PUBLIC_DOMAIN")
    if railway_domain:
        ALLOWED_HOSTS.extend([
            railway_domain,
            f"*.{railway_domain}",
        ])
    
    # Add any custom domains
    custom_domains = get_env('ALLOWED_DOMAINS', '')
    if custom_domains:
        ALLOWED_HOSTS.extend([domain.strip() for domain in custom_domains.split(',')])
    
    # Always allow localhost and Railway health checks
    ALLOWED_HOSTS.extend(["localhost", "127.0.0.1", "0.0.0.0", "healthcheck.railway.app", ""])
    
    # Remove duplicates while preserving order
    seen = set()
    ALLOWED_HOSTS = [host for host in ALLOWED_HOSTS if not (host in seen or seen.add(host))]
else:
    # Development: Allow all hosts
    ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    "rest_framework.authtoken",
    'corsheaders',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'evoting.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'evoting.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Priority: DATABASE_URL > PG* env vars > local defaults
database_url = os.environ.get('DATABASE_URL')

if database_url:
    # Use DATABASE_URL if available (Railway provides this)
    DATABASES = {
        'default': dj_database_url.parse(database_url, conn_max_age=600)
    }
elif os.environ.get('PGDATABASE') and os.environ.get('PGHOST'):
    # Use individual PG* environment variables if set
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('PGDATABASE'),
            'USER': os.environ.get('PGUSER', 'postgres'),
            'PASSWORD': os.environ.get('PGPASSWORD', ''),
            'HOST': os.environ.get('PGHOST', 'localhost'),
            'PORT': os.environ.get('PGPORT', '5432'),
        }
    }
else:
    # Local development defaults
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': get_env('NAME'),
            'USER': get_env('USER'),
            'PASSWORD': get_env('PASSWORD'),
            'HOST': get_env('HOST'),
        }
    }

# Cache configuration for rate limiting
if get_env('REDIS_URL') and not DEBUG:
    # Production: Use Redis from environment (Railway, Upstash, etc.) with rate limiting
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': get_env('REDIS_URL'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
    RATE_LIMITING_ENABLED = True
    # Add django-ratelimit to installed apps only when enabled
    if 'django_ratelimit' not in INSTALLED_APPS:
        INSTALLED_APPS.append('django_ratelimit')
else:
    # Development: Use DummyCache (no rate limiting)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
    RATE_LIMITING_ENABLED = False
    # Remove django-ratelimit from installed apps when not enabled
    if 'django_ratelimit' in INSTALLED_APPS:
        INSTALLED_APPS.remove('django_ratelimit')

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5175",
    "http://localhost:5173",
    "http://127.0.0.1:5175",
    "http://127.0.0.1:5173",
    "https://kasec-evoting-7lkj.onrender.com"
]

# Add Railway domain dynamically
if get_env("RAILWAY_PUBLIC_DOMAIN"):
    railway_domain = get_env("RAILWAY_PUBLIC_DOMAIN")
    CORS_ALLOWED_ORIGINS.extend([
        f"https://{railway_domain}",
        f"http://{railway_domain}",
    ])

# For development, allow all origins
if get_env("DEBUG", default=False, cast=bool):
    CORS_ALLOW_ALL_ORIGINS = True



CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-student-id',
    'x-election-id',
    'x-voter-token',
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5175",
    "https://kasec-evoting-7lkj.onrender.com"
]

# Add Railway domain dynamically for CSRF
if get_env("RAILWAY_PUBLIC_DOMAIN"):
    railway_domain = get_env("RAILWAY_PUBLIC_DOMAIN")
    CSRF_TRUSTED_ORIGINS.extend([
        f"https://{railway_domain}",
        f"http://{railway_domain}",
    ])


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# Simple JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=2),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(hours=6),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(hours=12),
}

INSTALLED_APPS += ["rest_framework_simplejwt.token_blacklist"]

AUTH_USER_MODEL = "core.User"

VOTER_HMAC_KEY = get_env('VOTER_HMAC_KEY')
if not VOTER_HMAC_KEY:
    raise ValueError("No VOTER_HMAC_KEY set for production")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
    if not DEBUG
    else "django.contrib.staticfiles.storage.StaticFilesStorage"
)

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'security': {
            'format': '{levelname} {asctime} {ip} {user} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'django.log',
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'security.log',
            'formatter': 'security',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'security': {
            'handlers': ['security_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")] if os.path.exists(os.path.join(BASE_DIR, "static")) else []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (uploaded images)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Cloudinary Configuration (for production image uploads)
CLOUDINARY_CLOUD_NAME = get_env('CLOUDINARY_CLOUD_NAME', '')
CLOUDINARY_API_KEY = get_env('CLOUDINARY_API_KEY', '')
CLOUDINARY_API_SECRET = get_env('CLOUDINARY_API_SECRET', '')
